name: flutter_page_indicator
description: Page indicator for flutter, with multiple build-in layouts.
version: 0.0.3
author: JZoom <jzoom8112@gmail.com>
homepage: https://github.com/jzoom/flutter_page_indicator

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=0.1.4 <3.22.3"


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
